export default {
  FETCH_HOT_BLOGS: 1,
  FETCH_LATEST_BLOGS: 2,
  FETCH_MORE_LATEST_BLOGS: 3,
  FETCH_CATS: 4,
  GET_BLOG_DATE: 5,
  ADD_BLOG: 6,
  ADD_AUTH: 7,
  REMOVE_AUTH: 8,
  MOVE_START: 9,
  EDIT_AUTH: 10,
};
